---
- name: STAT; check if rclone is installed
  ansible.builtin.stat:
    path: /usr/bin/rclone
  register: rclone_binary

- name: SHELL; install rclone (there may be a better way, for later)
  ansible.builtin.shell:
    cmd: "curl https://rclone.org/install.sh | bash"
  when: rclone_binary.stat.exists == False

- name: SHELL; create configuration 
  ansible.builtin.shell:
    cmd: "rclone config create {{ minio_alias }} s3 provider Minio env_auth false access_key_id {{ minio_access_key }} secret_access_key {{ minio_secret_key }} endpoint {{ minio_cluster_url }} acl private"

- name: FILE; create a symlink for rclone 
  ansible.builtin.file:
    src: /usr/bin/rclone
    dest: /sbin/mount.rclone
    state: link

- name: FILE; create the mount point for the minio bucket 
  ansible.builtin.file:
    path: "/mnt/{{ minio_bucket_name }}"
    mode: 0755
    state: directory

- name: MOUNT; mount the minio bucket
  ansible.posix.mount:
    path: "/mnt/{{ minio_bucket_name }}"
    src: "{{ minio_alias }}:{{ minio_bucket_name }}"
    fstype: rclone
    opts: config=/root/.config/rclone/rclone.conf
    state: present
