---
- name: FILE; create the /opt/eddie/{{ minio_bucket_name }} directory
  file:
    path: "/opt/eddie/{{ minio_bucket_name }}"
    state: directory
    mode: 0755
    recurse: true

- name: TEMPLATE; copy over the template files
  template: 
    src: "{{ item }}.j2"
    dest: "/opt/eddie/{{ minio_bucket_name }}/{{ item}}"
  loop:
    - artifact-repository.yaml
    - eddie-secrets.yaml
    - minio-event-source.yaml
    - minio-secrets.yaml
    - model-update.yaml
    - sensor.yaml

# - name: FILE; create the {{ models_path }}
#   file:
#     path: "{{ models_path }}"
#     state: directory
#     mode: 0755
#     recurse: true

- name: git; clone the models repository
  git:
    repo: "https://oauth2:{{ dvc_git_token }}@{{ dvc_git_models_url }}"
    dest: "{{ models_path }}"
    version: "{{ (model_version_override == '') | ternary(dvc_branch | default('main'), model_version_override) }}"
    force: yes
    update: yes
    recursive: yes

- name: SHELL; dvc setup
  shell:
    cmd: "dvc remote modify --local coalesce user {{ cyverse_user }} && dvc remote modify --local coalesce password '{{ cyverse_pass }}'"
  args:
    chdir: "{{ models_path }}"


- name: SHELL; apply the k8s resources
  shell:
    cmd: "kubectl apply -f /opt/eddie/{{ minio_bucket_name }}"